# значение расчитано, исходя из размера базового json`а
# с тремя полями (product_id, producer_name, price) * 100 элементов
maxBodyRequestSize: 12288
# кол-во работающих потоков, опрашивающих пул данных распределенный по партициям.
# каждый воркер работает строго со своей партицией.
workerCount: 7
# кол-во (мс) которое поток будет ждать перед повторной попыткой опросить пул
waitIntervalMillis: 1000